var json = {
	"record1":{
		"familySelect": ["Side of Family:", "Immediate"],
		"firstName": ["First Name:", "Abraham"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "32"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Much more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2011-11-11"],
		"comments": ["Doctor's Comments:", "Healthy"]
	},
	"record2":{
		"familySelect": ["Side of Family:", "Immediate"],
		"firstName": ["First Name:", "Matthew"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "32"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Much more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2010-11-11"],
		"comments": ["Doctor's Comments:", "Healthy"]
	},
	"record3":{
		"familySelect": ["Side of Family:", "Immediate"],
		"firstName": ["First Name:", "Wanda"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "65"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Average"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-11-11"],
		"comments": ["Doctor's Comments:", "Old"]
	},
	"record4":{
		"familySelect": ["Side of Family:", "Immediate"],
		"firstName": ["First Name:", "Bill"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "45"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Average"],
		"exerciseHabits": ["Exercising Habits:", "Much less often than most"],
		"diabetes": ["Diabetes:", "Yes"],
		"docVisit": ["Last Checkup:", "2001-11-11"],
		"comments": ["Doctor's Comments:", "Overweight"]
	},
	"record5":{
		"familySelect": ["Side of Family:", "Immediate"],
		"firstName": ["First Name:", "Arthur"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "63"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Much more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2009-11-11"],
		"comments": ["Doctor's Comments:", "Very Healthy"]
	},
	"record6":{
		"familySelect": ["Side of Family:", "Maternal"],
		"firstName": ["First Name:", "Nancy"],
		"lastName": ["Last Name:", "Markham"],
		"age": ["Age:", "58"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "A little un healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2009-11-11"],
		"comments": ["Doctor's Comments:", "Needs more exercise and to eat healthier"]
	},
	"record7":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Diane"],
		"lastName": ["Last Name:", "Ennis"],
		"age": ["Age:", "57"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "A little less often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2005-11-11"],
		"comments": ["Doctor's Comments:", "Needs to cut down on sugar intake."]
	},
	"record8":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Rochelle"],
		"lastName": ["Last Name:", "Hoggatt"],
		"age": ["Age:", "58"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "I don't exercise"],
		"diabetes": ["Diabetes:", "Yes"],
		"docVisit": ["Last Checkup:", "2012-11-11"],
		"comments": ["Doctor's Comments:", "Overweight"]
	},
	"record9":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Cynthia"],
		"lastName": ["Last Name:", "Chute"],
		"age": ["Age:", "60"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "A little healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2010-1-11"],
		"comments": ["Doctor's Comments:", "Need to exercise more regularly."]
	},
	"record10":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Joseph"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "90"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Average"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "Yes"],
		"docVisit": ["Last Checkup:", "1997-11-11"],
		"comments": ["Doctor's Comments:", "Deceased."]
	},
	"record11":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Sylvia"],
		"lastName": ["Last Name:", "Kowitz"],
		"age": ["Age:", "88"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "A little unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "I don't exercise"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "1994-4-11"],
		"comments": ["Doctor's Comments:", "Deceased."]
	},
	"record12":{
		"familySelect": ["Side of Family:", "Maternal"],
		"firstName": ["First Name:", "Edmond"],
		"lastName": ["Last Name:", "Markham"],
		"age": ["Age:", "100"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "A little healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "A little more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "1993-7-11"],
		"comments": ["Doctor's Comments:", "Deceased."]
	},
	"record13":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Charlotte"],
		"lastName": ["Last Name:", "Hager"],
		"age": ["Age:", "39"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2008-11-21"],
		"comments": ["Doctor's Comments:", "Cut back on fatty foods."]
	},
	"record14":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Adam"],
		"lastName": ["Last Name:", "Chute"],
		"age": ["Age:", "39"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "A little less often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-1-21"],
		"comments": ["Doctor's Comments:", "Limit food portions."]
	},
	"record15":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Eric"],
		"lastName": ["Last Name:", "Olsen"],
		"age": ["Age:", "31"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "A little less often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2000-10-14"],
		"comments": ["Doctor's Comments:", "Lay off the Doughnuts!"]
	},
	"record16":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Celia"],
		"lastName": ["Last Name:", "Ennis"],
		"age": ["Age:", "24"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Average"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-6-11"],
		"comments": ["Doctor's Comments:", "Healthy"]
	},
	"record17":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Max"],
		"lastName": ["Last Name:", "Ennis"],
		"age": ["Age:", "28"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Much more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-1-11"],
		"comments": ["Doctor's Comments:", "Healthy"]
	},
	"record18":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Samuel"],
		"lastName": ["Last Name:", "Ennis"],
		"age": ["Age:", "22"],
		"sex": ["Sex:", "Male"],
		"eatHabits": ["Eating Habits:", "Much unhealthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Average"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-7-11"],
		"comments": ["Doctor's Comments:", "Overweight, exercise more and eat less."]
	},
	"record19":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Tina"],
		"lastName": ["Last Name:", "Revel"],
		"age": ["Age:", "40"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "I don't exercise"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-3-11"],
		"comments": ["Doctor's Comments:", "Healthy"]
	},
	"record20":{
		"familySelect": ["Side of Family:", "Paternal"],
		"firstName": ["First Name:", "Valerie"],
		"lastName": ["Last Name:", "Hager"],
		"age": ["Age:", "17"],
		"sex": ["Sex:", "Female"],
		"eatHabits": ["Eating Habits:", "Much healthier than most"],
		"exerciseHabits": ["Exercising Habits:", "Much more often than most"],
		"diabetes": ["Diabetes:", "No"],
		"docVisit": ["Last Checkup:", "2012-5-15"],
	}
};